connect:
  hostname: "http://localhost:3000"
  directory: "/Users/klakshminarayanan/enphase/ens-summit/public"

mqtt:
  ca_file_path: "/Users/klakshminarayanan/enphase/ens-summit/public/verisign-root-ca.pem"
  aws_mqtt_endpoint: "a1n5u982zrd0mu.iot.us-east-1.amazonaws.com"
  data_stream: "devices/data-stream"
